version: "3.7"

services:

  be:
    build:
      context: be/
      target: production
    restart: unless-stopped
    ports:
      # This needs to match BACK_END_API_PORT environment variable
      - "3001:3001"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: app_user
      DB_PASSWORD: my_super_password
      DB_NAME: my_app
      BACK_END_API_PORT: 3001
      FRONT_END_API_HOST: my-awesome-website.com
      FRONT_END_API_PORT: "80, 443"

  fe:
    build:
      context: fe/
      target: production
    restart: unless-stopped
    ports:
      # Change port 3000 to anavailable port that will be
      # mapped in your reverse-proxy
      - "3000:80"
    
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: my_app
      MYSQL_USER: app_user
      MYSQL_PASSWORD: oas87nyfrc8odvs7
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - type: bind
        source: ./db
        target: "/var/lib/mysql"

volumes:
  be:
  fe:
  db: