version: "3.7"

services:

  be:
    image: jscdroiddev/docker-nodejs-mariadb-be:latest
    restart: unless-stopped
    ports:
      # This needs to match BACK_END_API_PORT environment variable
      - "3001:3001"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_USER: app_user
      DB_PASSWORD: my_super_password
      DB_NAME: my_app
      BACK_END_API_PORT: 3001
      FRONT_END_API_HOST: localhost
      FRONT_END_API_PORT: "3000"

  fe:
    image: jscdroiddev/docker-nodejs-mariadb-fe:latest
    restart: unless-stopped
    ports:
      # Change port 3000 to anavailable port that will be
      # mapped in your reverse-proxy
      - "3000:80"
    
  db:
    image: mariadb:latest
    restart: unless-stopped    
    environment:
      MYSQL_DATABASE: my_app
      MYSQL_USER: app_user
      MYSQL_PASSWORD: my_super_password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - "./my_data:/var/lib/mysql"

volumes:
  db: