name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - created

  workflow_dispatch:

jobs:

  deploy:
#    needs: [build-fe, build-be]
    runs-on: ubuntu-latest
    #if: github.event_name == 'release' && github.event.action == 'created'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Remote deploy
        run: |
          chmod u+x "${GITHUB_WORKSPACE}/.github/docker-deploy.sh"
          "${GITHUB_WORKSPACE}/.github/docker-deploy.sh" "${{ secrets.SERVER_DB_PASSWORD }}" "${{ secrets.DEPLOY_KEY }}" "${{ secrets.DEPLOY_KNOWN_HOST }}" "${{ secrets.DEPLOY_USERNAME }}" "${{ secrets.DEPLOY_SERVER }}"

      - name: Deploy database
        run: |
          chmod u+x "${GITHUB_WORKSPACE}/.github/db-update.sh"
          "${GITHUB_WORKSPACE}/.github/db-update.sh" "${{ secrets.DEPLOY_USERNAME }}" "${{ secrets.DEPLOY_SERVER }}" "my_user" "${{ secrets.SERVER_DB_PASSWORD }}" "my_app"
