name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  fe:
    name: front-end
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        cd fe
        yarn install --frozen-lockfile
        yarn test:coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./fe/coverage/coverage-final.json
        fail_ci_if_error: true
        verbose: true
  be:
    name: back-end
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        cd be
        yarn install --frozen-lockfile
        yarn test:coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./be/coverage/coverage-final.json
        fail_ci_if_error: true
        verbose: true
